apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configurations-deployment.yaml
  - configurations-svc.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: configurations
    path: prod_patches/configurations-prod.yaml