apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configurations-deployment.yaml
  - configurations-svc.yaml
  
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: configurations-svc
    path: local_patches/configurations-svc-dev.yaml